# Generated by Django 4.2.5 on 2024-01-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=128)),
                ('sender_surname', models.CharField(max_length=128)),
                ('from_address', models.CharField(max_length=128)),
                ('to_address', models.CharField(max_length=128)),
                ('from_index', models.CharField(max_length=128)),
                ('to_index', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('parcel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_type', to='mainapp.parceltype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=128)),
                ('sender_surname', models.CharField(max_length=128)),
                ('from_address', models.CharField(max_length=128)),
                ('to_address', models.CharField(max_length=128)),
                ('from_index', models.CharField(max_length=128)),
                ('to_index', models.CharField(max_length=128)),
                ('letter_weight', models.PositiveIntegerField(default=0)),
                ('letter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_type', to='mainapp.lettertype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
