# Generated by Django 4.2.5 on 2024-01-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertype',
            name='letter_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='mainapp.lettertype'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='mainapp.parceltype'),
        ),
        migrations.AlterField(
            model_name='parceltype',
            name='parcel_type',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
