# Generated by Django 4.2.5 on 2024-01-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_lettertype_letter_type_alter_letter_letter_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='letter_type',
            field=models.IntegerField(choices=[(1, 'Ordinary Letter'), (2, 'Registered Letter'), (3, 'Valuable Letter'), (4, 'Express Letter')], default=1),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_type',
            field=models.IntegerField(choices=[(1, 'Small Parcel'), (2, 'Ordinary Parcel'), (3, '1-st Class Parcel'), (4, 'Valuable Parcel'), (5, 'International Parcel'), (6, 'Express Parcel')], default=1),
        ),
        migrations.DeleteModel(
            name='LetterType',
        ),
        migrations.DeleteModel(
            name='ParcelType',
        ),
    ]
