# Generated by Django 4.2.5 on 2024-01-23 22:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_letter_letter_type_alter_parcel_parcel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
