# Generated by Django 4.2.5 on 2024-01-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_parcel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='from_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='letter',
            name='to_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='from_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='to_index',
            field=models.PositiveIntegerField(),
        ),
    ]
